#ifndef DEF_ACTIONS_H
#define DEF_ACTIONS_H

#define DEF_MENU_MAIN_FILE_NEW 100
#define DEF_MENU_MAIN_FILE_OPEN 101
#define DEF_MENU_MAIN_FILE_SAVE 102
#define DEF_MENU_MAIN_FILE_SAVEAS 103
#define DEF_MENU_MAIN_FILE_EXIT 109
#define DEF_MENU_MAIN_EDIT_CONF 110
#define DEF_MENU_MAIN_EDIT_MODE 111
#define DEF_MENU_MAIN_RUN_ALL 120
#define DEF_MENU_MAIN_HELP_ABOUT 190

#endif
